services:
  backend:
    build: ./Back/mysite
    ports:
      - "8000:8000"  # Assurez-vous que ce port est unique et correct pour votre application backend
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=mydb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_PORT=3306

  frontend:
    build: ./Front/mysite
    ports:
      - "3001:3000"  # Assurez-vous que ce port est correct pour votre application frontend

  db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mydb
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

volumes:
  mysql_data: